version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "8080:8080"
    volumes:
      - /data/jenkins_home:/var/jenkins_home
    restart: unless-stopped

volumes:
  jenkins_home:
    external: false

